version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    assignees:
      - "alexanderczigler"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      dev-deps:
        patterns:
          - "*"
        dependency-type: "development"
    assignees:
      - "alexanderczigler"
