// This file is auto-generated. Do not edit manually.

export type Recipes =
  | 'bouillabaisse'
  | 'broccoligratäng'
  | 'caesarsallad'
  | 'chana-daal'
  | 'chicken-tikka-masala'
  | 'currykyckling'
  | 'daal'
  | 'färdig-risotto'
  | 'grekisk-sallad'
  | 'holy-caesar'
  | 'kinesisk-gurksallad'
  | 'kokoskyckling'
  | 'krämig-grönkål'
  | 'krämig-lax'
  | 'laxinoa'
  | 'laxokado'
  | 'linsgryta'
  | 'mapu-tofu'
  | 'mexicali'
  | 'pasta-pesto'
  | 'pasta-tomatsås'
  | 'pepparbiff'
  | 'pestolasagne'
  | 'pokebowl'
  | 'räkrisotto'
  | 'skaldjursomelett'
  | 'spenat-och-fetaostpaj'
  | 'svamprisotto'
  | 'sötpotatisbowl'
  | 'tofu-stroganoff'
  | 'tonfisksallad'
  | 'tortellini-con-brodo'
  | 'ugnsbakad-falukorv'
  | 'ugnsbakad-lax';
