name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v5

      - name: 🔧 Build
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
      - run: |
          npm ci
          npm run lint
          npm run build
